# Websites global values, like the navigation

nav:
  main:
    Projects: /projects
    Services: /services
    Publications: /publications
    Contact: /contact
  service:
    Legal notice: /legal-notice
    Privacy policy: /data-privacy-policy