# Websites global values, like the navigation

addons: ["Project"]
nav:
  main:
    Services: /services
    Projects: /works
    Publications: /howto
    Contact: /contact
  service:
    Legal notice: /legal-notice
    Privacy policy: /data-privacy-policy