# Websites global values

navbar:
  structure:
    Projects: /projects
    Services: /services
    Publications: /publications
    
#   Services: /services
#   Works: /works
#   Articles: /howto
#   Contact: /contact