# Websites global values, like the navigation

nav:
  main:
    Projects: /works
    Services: /services
    Publications: /howto
    Contact: /contact
  service:
    Legal notice: /legal-notice
    Privacy policy: /data-privacy-policy