export const faCss3Alt: IconDefinition;
export const faLinkedinIn: IconDefinition;
export const faVuejs: IconDefinition;
export const faDiscord: IconDefinition;
export const faAngular: IconDefinition;
export const faWordpress: IconDefinition;
export const faReact: IconDefinition;
export const faLess: IconDefinition;
export const faFacebookF: IconDefinition;
export const faInstagram: IconDefinition;
export const faHtml5: IconDefinition;
export const faSass: IconDefinition;
export const faJs: IconDefinition;
export const faGithub: IconDefinition;
export const faPhp: IconDefinition;
export const faTwitter: IconDefinition;
export const faTelegram: IconDefinition;
export const faTelegramPlane: IconDefinition;
export const faNodeJs: IconDefinition;
import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const fab: IconPack;