export const faRightFromBracket: IconDefinition;
export const faSignOutAlt: IconDefinition;
export const faBars: IconDefinition;
export const faNavicon: IconDefinition;
export const faLock: IconDefinition;
export const faShieldCheck: IconDefinition;
export const faRightToBracket: IconDefinition;
export const faSignInAlt: IconDefinition;
export const faChessKnight: IconDefinition;
export const faUnlock: IconDefinition;
export const faAddressCard: IconDefinition;
export const faContactCard: IconDefinition;
export const faVcard: IconDefinition;
export const faLanguage: IconDefinition;
export const faBadgeCheck: IconDefinition;
export const faXmarkLarge: IconDefinition;
export const faXmark: IconDefinition;
export const faClose: IconDefinition;
export const faMultiply: IconDefinition;
export const faRemove: IconDefinition;
export const faTimes: IconDefinition;
export const faThumbsUp: IconDefinition;
export const faNotdef: IconDefinition;
import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const far: IconPack;